### ISSUE TITLE
[Question] How to focus field

### ISSUE THREAD

**Issue by Nikodermus** [nathanstitt/react-braintree-fields#17]
Currently I'm using the hostedfields as:
```
                    <label htmlFor="securityCode">CVV</label>
                    <HostedField
                        id="securityCode"
                        type="cvv"
                        placeholder="123"
                        className="credit-card-dialog-body__field"
                    />
```

I would like to be able to focus the field from the outside label, is this possible with the current implementation?

**Comment by nathanstitt** [comment]
Hi @Nikodermus, yes it should be possible but you'll have to wire that up yourself since the HostedField is actually an iframe so the normal DOM techniques won't work.

To do so you can attach a `onClick` listener to the label and then calling `focus()` on a reference to the HostedField, something like this:

```jsx

class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.fieldRef = React.createRef();
  }
  render() {
return (
    <label htmlFor="securityCode" onClick={ () => this.fieldRef.current.focus() }>CVV</label>
    <HostedField
      ref={this.fieldRef}
      id="securityCode"
      type="cvv"
       placeholder="123"
        className="credit-card-dialog-body__field"
   />
)
  }
}

```

That should do it, please reply if it doesn't for some reason

**Comment by Nikodermus** [comment]
It did work, thanks for the awesome job
